### ISSUE TITLE
RoleManager

### ISSUE THREAD

**Issue by chemitaxis** [saan800/SaanSoft.AspNet.Identity3.MongoDB#2]
Can I use RoleManager with DI in the example? I always have an error when try to use in a controller... Thanks!

**Comment by saan800** [comment]
Yes, they should be registered in [Startup.cs](https://github.com/saan800/SaanSoft.AspNet.Identity3.MongoDB/blob/master/samples/Web.MongoDBIdentitySample/Startup.cs#L42) as part of the `services.AddIdentity<ApplicationUser, IdentityRole>()` - which is part of the Microsoft.AspNet.Identity library.

```
public void ConfigureServices(IServiceCollection services)
{
	services.AddIdentity<ApplicationUser, IdentityRole>()
			.AddMongoDBIdentityStores<ApplicationDbContext, ApplicationUser, IdentityRole, string>(options =>
			{
				options.ConnectionString = Configuration["Data:DefaultConnection:ConnectionString"]; 
			})
			.AddDefaultTokenProviders();

	// and other services config stuff
}
```

I have however added the DI setup of all the User and Role store interfaces that are implemented by SaanSoft.AspNet.Identity3.MongoDB (only registered UserStore and RoleStore before) in a new nuget package - https://www.nuget.org/packages/SaanSoft.AspNet.Identity3.MongoDB/1.0.0-rc1-final-09

Check out the sample app's [DiTestController](https://github.com/saan800/SaanSoft.AspNet.Identity3.MongoDB/blob/master/samples/Web.MongoDBIdentitySample/Controllers/DiTestController.cs) if you need to check.
