### ISSUE TITLE
ObjectId error parse

### ISSUE THREAD

**Issue by chemitaxis** [saan800/SaanSoft.AspNet.Identity3.MongoDB#4]
Hi! I had a user collection created with Identity 2.0 and my Id stored in the database is the type ObjectId. 

Now, with Identity 3.0 and using your package, I have this error:

> FormatException: Cannot deserialize a 'String' from BsonType 'ObjectId'.

The problem is that in the package it uses GUID to create the User Id, but my old collection uses ObjectId. Any ideas how to solve? Thanks!!

**Comment by saan800** [comment]
Hi chemitaxis 

When you setup your application specific instance of IdentityUser, do you inherit from just pain old IdentityUser - eg

```
public class ApplicationUser : IdentityUser
{
}
```

OR do you specify the id type? eg

```
public class ApplicationUser : IdentityUser<ObjectId>
{
}
```

Plain old `IdentityUser` is actually configured as `IdentityUser<string>`

Hope this helps, let me know how you get on
Saan

**Comment by saan800** [comment]
Just on a side note - when Microsoft re-wrote Identity v2 -> Identity v3, they may have changed the underlying data schema for users (I'm not entirely sure if they did or not as I haven't used Identiy v2 before). 

You'll need to check your existing mongoDB users to see if they still match the schema - which can be found here https://github.com/saan800/SaanSoft.AspNet.Identity3.MongoDB/blob/master/src/SaanSoft.AspNet.Identity3.MongoDB/IdentityUser.cs

You may need a migration script for your DB.

**Comment by saan800** [comment]
Closing due to no response on suggestions to try

**Comment by chemitaxis** [comment]
Thanks @saan800 I have solved :)
