### ISSUE TITLE
Do you plan to release a new version of the library soon?

### ISSUE THREAD

**Issue by CamiloBernal** [saan800/SaanSoft.AspNet.Identity3.MongoDB#6]
Hello, first of all, thank you for this great library; It has been a great help to me and I have been implementing a new project. Really it is going great.

However, I wanted to ask if you have plans to release a new version of your library soon. This was mainly to see if it is possible that you add support for new versions of the official MongoDB driver for .Net (3.2 or higher).

It has happened that I have tried to use the new versions of driver mongo .Net and most of the time it works, however, randomly the new version of the driver has trouble serialize/deserialize some objects in your library (I think they are as inherited of Asp.Net Identity).

I would appreciate if you share your release plans for this library in the near future.

Again, thank you for this great contribution to the community.

Cordially,

Camilo Bernal

**Comment by saan800** [comment]
Hi Camilo

I'm not sure which version of mongo driver you mean. On nuget the official driver only goes up to 2.2.3 (https://www.nuget.org/packages/MongoDB.Driver/)

Saan
